name: 'Build with Maven'
description: 'Run Maven build by updating apt and installing Maven'

inputs:
  APT_UPDATE_CMD:
    description: 'Command to update apt'
    required: true
    default: 'sudo apt-get update'
  APT_INSTALL_MAVEN_CMD:
    description: 'Command to install Maven'
    required: true
    default: 'sudo apt-get install maven -y'
  PROJECT_DIR:
    description: 'Directory of the Maven project'
    required: true
    default: '.'
  MAVEN_GOAL:
    description: 'Maven goal to run'
    required: true
    default: 'install'

runs:
  using: 'node16'
  main: 'index.js'

