name: 'reusable workflow'
description: "A reusable workflow for building and sending Teams notifications"

inputs:
  accesstoken:
    description: "GitHub access token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout index action
      uses: actions/checkout@v3
      with:
        repository: venkyy8/index-repo  # ✅ Corrected line
        ref: main
        path: ./venky

    - name: Run build
      uses: ./venky
      with:
        accesstoken: ${{ inputs.accesstoken }}
