name: 'Reusable Email Workflow'
description: "A reusable workflow for sending notification emails via Node.js"

runs:
  using: "composite"
  steps:
    - name: Checkout index-repo
      uses: actions/checkout@v3
      with:
        repository: venkyy8/index-repo
        ref: main
        path: ./venky

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ./venky

    - name: Run index.js to send email
      run: node index.js
      shell: bash
      working-directory: ./venky
